org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
mc_version=1.20.1
mc_version_range=[1.20,1.21)
neo_version=47.1.65
neo_version_range=[47.1,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=mekanism_trimming
mod_group=krelox.mekanism_trimming
mod_name=Mekanism Trimming
mod_version=1.20.1-1.0
mod_license=MIT License
mod_url=https://modrinth.com/mod/mekanism-trimming
mod_github=https://github.com/KreloX/mekanism-trimming
mod_credits=
mod_authors=KreloX
mod_description=Makes armor trimmable with materials from the Mekanism mod.
pack_format_number=15

## Dependency Properties
emi_version=1.1.22+1.20.1
mekanism_version=1.20.1-10.4.0.14
